service: corrigo-pro-integration-poc

frameworkVersion: '3'  # Ensure you are using Serverless Framework version 3

custom:
  serverless-offline:
    noPrependStageInUrl: true
  useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-1
  environment:
    timeout: 899  # must be <= 900
  plugins:
    - serverless-esbuild
  tracing:
    apiGateway: true
    lambda: true
functions:
  app:
    handler: handler/customHandler.handler
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
          cors: true  # shorthand for allowing CORS for all origins and headers
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  cronJobs:
    handler: handler/workOrderAndInvoiceDetailsUpdate.handler
    timeout: 899
    events:
      - schedule:
          rate: rate(1 minute)
plugins:
  # - serverless-http
  - serverless-offline
  - serverless-dotenv-plugin
